name: extract_chinese_strings
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  csv: ^5.0.0
  analyzer: ^2.1.0
  args: ^2.2.0
  process_run: ^0.12.1+1

dev_dependencies:
